### PR TITLE
Making it more customizable + fix some inconsequencies at reopening the modal

### PR DESCRIPTION
**Pull request by balazsherczeg**
Changes:

- Make all the elements in the dialog customizable, by adding a `styles` props, to possibly override default styling.
- Make rating component customizable through props or passing the rating component of your own choice. Defaults to `AirBnBRating`.
- When the review is empty, rather then showing an error message, disable _Send_ button. It happens, if there is a style declaration for the disabled state of the button.
- Make modal customizable, so you could set animation type by props. 
- Put a _Cancel_ button for the review view.
- Fix modal, that `onRequestClose` should work.
- Make it a fully controlled component to fix some problems when reopening the dialog: 1.) the selected stars are displayed by the props, but the send button behaves by the state, 2.) in some cases the `isModalOpen` was different in props and state.
- Reset the dialog at the reopening (selected stars, view, review, if sent).
- Remove deprecated lifecycle methods.

### CODE REVIEW

**Review by omeraplak — APPROVED** [review]

**Comment by omeraplak** [comment]
@balazsherczeg Hi,
Thanks for PR!. Awesome contribution. Could you update README with new props?

**Comment by balazsherczeg** [comment]
Documentation updated.

**Review by omeraplak — APPROVED** [review]

**Comment by omeraplak** [comment]
@balazsherczeg Hi,
Could you fix conflicts?

**Comment by balazsherczeg** [comment]
Hello, I'll take a look at it.

**Comment by omeraplak** [comment]
@balazsherczeg Hi
Thank you!

**Comment by omeraplak** [comment]
@balazsherczeg Hi,
Bumped 1.1.0!

**Comment by balazsherczeg** [comment]
Nice :)

**Pull request merged**
